version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    user: root
    image: damoncheng/public:jenkins
    deploy:
      replicas : 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
      - "50000:50000"
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
